[package]
name = "oxidec"
version = "2.0.0"
edition = "2021"
description = "Advanced eye-candy manager written in Rust"
license = "GPL-3.0"
repository = "https://github.com/mrtnvgr/oxidec"
keywords = ["colorscheme", "wallpaper", "theme", "linux", "cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
cli-panics = "0.1.2"
colorsys = "0.7"
env_logger = "0.11.11"
home = "0.5"
log = "0.4"
nu-ansi-term = "0.50.3"
rand = "0.10.2"
regex = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.28", features = ["derive", "strum_macros"] }
upon = "0.11"
which = "8.0"

[features]
default = ["colorschemes", "wallpapers", "themes"]
colorschemes = []
wallpapers = []
themes = ["colorschemes", "wallpapers"]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
