[package]
name = "oxidec"
version = "2.0.0"
edition = "2021"
description = "Advanced eye-candy manager written in Rust"
license = "GPL-3.0"
repository = "https://github.com/mrtnvgr/oxidec"
keywords = ["colorscheme", "wallpaper", "theme", "linux", "cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
cli-panics = "0.1.2"
env_logger = "0.11.11"
home = "0.5"
log = "0.4"
rand = "0.10.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
which = "8.0"
strum = { version = "0.28", features = ["derive", "strum_macros"] }
colorsys = { version = "0.7", optional = true }
nu-ansi-term = { version = "0.50.3", optional = true }
regex = { version = "1.10", optional = true }
upon = { version = "0.11", optional = true }

[features]
default = ["colorschemes", "wallpapers", "themes"]
colorschemes = ["dep:colorsys", "dep:nu-ansi-term", "dep:regex", "dep:upon"]
wallpapers = []
themes = ["colorschemes", "wallpapers"]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
